CREATE DATABASE accidentes;
USE accidentes;
CREATE TABLE accidentes_data (
    ID INT,
    Source VARCHAR(50),
    Severity INT,
    Start_Time DATETIME,
    End_Time DATETIME,
    Start_Lat DOUBLE,
    Start_Lng DOUBLE,
    End_Lat DOUBLE,
    End_Lng DOUBLE,
    `Distance(mi)` DOUBLE,
    Description TEXT,
    Street TEXT,
    City VARCHAR(100),
    County VARCHAR(100),
    State VARCHAR(10),
    Zipcode VARCHAR(20),
    Country VARCHAR(10),
    Timezone VARCHAR(50),
    Airport_Code VARCHAR(10),
    Weather_Timestamp DATETIME,
    `Temperature(F)` DOUBLE,
    `Wind_Chill(F)` DOUBLE,
    `Humidity(%)` DOUBLE,
    `Pressure(in)` DOUBLE,
    `Visibility(mi)` DOUBLE,
    Wind_Direction VARCHAR(20),
    `Wind_Speed(mph)` DOUBLE,
    `Precipitation(in)` DOUBLE,
    Weather_Condition VARCHAR(100),
    Amenity BOOLEAN,
    Bump BOOLEAN,
    Crossing BOOLEAN,
    Give_Way BOOLEAN,
    Junction BOOLEAN,
    No_Exit BOOLEAN,
    Railway BOOLEAN,
    Roundabout BOOLEAN,
    Station BOOLEAN,
    Stop BOOLEAN,
    Traffic_Calming BOOLEAN,
    Traffic_Signal BOOLEAN,
    Turning_Loop BOOLEAN,
    Sunrise_Sunset VARCHAR(10),
    Civil_Twilight VARCHAR(20),
    Nautical_Twilight VARCHAR(20),
    Astronomical_Twilight VARCHAR(20)
);
INSERT INTO accidentes (
ID, Source, Severity, Start_Time, End_Time,
Start_Lat, Start_Lng, Distance_mi,
Description, Street, City, County, State, Zipcode, Country,
Temperature_F, Humidity, Weather_Condition
)
VALUES (
'A-1001', 'Source2', 2,
'2026-04-10 08:15:00', '2026-04-10 08:45:00',
41.8781, -87.6298, 0.02,
'Minor collision causing light traffic delay on I-90.',
'I-90', 'Chicago', 'Cook', 'IL', '60601', 'US',
55.0, 78.0, 'Clear'
);